version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "5173:5173" # Mappez le port de Vite
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]

